### ISSUE TITLE
OvertTheBox on Raspberry 1

### ISSUE THREAD

**Issue by NyKo24** [ovh/overthebox#124]
Hello,

Is it possible to run OverTheBox on a raspberry 1?
I saw that you had made a version for the raspberry 3, is it possible to adapt it for the 1? If so, can you tell me how?

Thank you

**Comment by angt** [comment]
Hi,
Yes it is possible, I'm building an rpi1 image for you let us know if it works :)

**Comment by NyKo24** [comment]
Great !! thank you very much ! ;) where I can find the image link ?

**Comment by angt** [comment]
You can download it here:
http://213.32.73.166:8000/angt/overthebox/add-config-rpi1/targets/brcm2708/bcm2708/otb-v2.11-7-g7dcb49d-v0.2.10-1102-g424d248-brcm2708-bcm2708-rpi-ext4-sdcard.img.gz

**Comment by NyKo24** [comment]
Thank’s lot !!!
I test this night or tomorrow and I tell you the result ;) 
But first, I do cancel my order on Amazon for RPI 3 :D

**Comment by NyKo24** [comment]
Update : 
I write image on raspberry SD card, I power it and... it's works !!
when I try to access to overthebox.ovh I get the RPI OverTheBox homepage 

I continue to test and I up this topic.

**Comment by angt** [comment]
Good news !
It would be great if you could run `glorytun bench` and post the result :)

**Comment by jyme** [comment]
Hi,

I see it's possible to works overthebox on a rpi 1 :D. But impossible to build correctly an image or download it with your link.

Do you think is it possible to explain me how have you done or reupload your build ? :).

Thank you
