### ISSUE TITLE
Overthebox under raspberry 2

### ISSUE THREAD

**Issue by Glummy64** [ovh/overthebox#139]
Is There a img for rpi 2 or the img for rpi should work ?

**Comment by angt** [comment]
Hi
I tried to build an rpi2 image without success, you can take a look at the [build](https://circleci.com/gh/angt/overthebox/316) and the [commit](https://github.com/angt/overthebox/commit/d87fd8b139831d4891301436e4d15b4c9a6099e8).
I'll not dig deeper as this platform is not in our roadmap for now but I'll ping you if I found something
Best regards
