### ISSUE TITLE
No internet connection with an OpenVPN connection behind OverTheBox

### ISSUE THREAD

**Issue by NyKo24** [ovh/overthebox#147]
Hi,

I set up an OpenVPN server on Scaleway with our server image, I install & configure Tunnelblick on my Mac, but when Tunneldick are connected with my VPN, I can't access any website, but I can make ping or SSH connection.

I try same configuration with my iphone in tethering and it's works...

How to ?

Thank's

**Comment by PouuleT** [comment]
Hello!
At first glance, it seems you're encountering a MTU problem

OverTheBox is securing its connexion through a tunnel, so there is already an overhead reducing the size of the packets
When trying to use a tunnel inside a tunnel, you might encounter a MTU problem

Have you tried reducing your MTU on the client side?
You could try with something like 1200 and higher the value later if it works

**Comment by NyKo24** [comment]
Thank’s for you reply !

No I haven’t try to reduce MTU on my OverTheBox, I will try !

**Comment by PouuleT** [comment]
You should try to reduce the MTU of the tunnel interface on your client
side (laptop or whatever device you are using), not on the OTB itself

The goal is that when your device using your VPN negotiate a TCP
connection, it will use this reduced MTU allowing it to pass through the
two layers of tunnels
Le mar. 27 févr. 2018 à 23:46, Nicolas Bordes <notifications@github.com> a
écrit :

**Comment by NyKo24** [comment]
Hi @PouuleT 
I try to reduce my MTU on my Mac (setting => networks => hardware => configurations manually) 
Configure input ask me a value between 1280 and 1500 (default value) I enter 1280, but I have same issue... 

Any Idea ?
