### ISSUE TITLE
Where is the script required by the vps server?

### ISSUE THREAD

**Issue by suyuan168** [ovh/overthebox#178]
Where is the script required by the vps server?

**Comment by angt** [comment]
Hi,
The server part is not provided as it is particularly complicated to install and use. Our platform is built to provide a service to thousands of customers and therefore does not match the need of a single one. That said, if you use the master branch (next 0.7) it is very easy to install the server part on a vps using docker-compose with [mudock](https://github.com/angt/mudock). A script `otb-configure-glorytun` is available on the client to setup a custom server.
Best regards.

**Comment by angt** [comment]
if you have a problem do not hesitate to report it.

**Comment by suyuan168** [comment]
I am a Chinese customer. Can you use this project on the OVH server VPS? What if I need to deploy a server in China?
