### ISSUE TITLE
VPS support

### ISSUE THREAD

**Issue by JorgeMoort89** [ovh/overthebox#197]
Hi @angt,
I can't figure out how can I set up the https://github.com/angt/mudock on my personal VPS, do you have some documentation about?

**Comment by BenoitAnastay** [comment]
@JorgeMoort89 Checkout glorytun and OpenMPTCProuter

for moddock install docker compose and run docker-compose run

**Comment by angt** [comment]
Hi @JorgeMoort89 
You can run the script `otb-configure-glorytun` (via ssh) and follow the instructions to link your device to your mudock :)
