### ISSUE TITLE
New webpage dont let you setup network

### ISSUE THREAD

**Issue by BenoitAnastay** [ovh/overthebox#200]
The new landing page when you do a fresh install don't let you go to network settings and you need network to register a device.

**Comment by angt** [comment]
Hi,

First of all, you use the "development" version, if you want a stable product, you can have a look here: http://downloads.overthebox.net/stable/targets/x86/64/.

I'm not sure about your current configuration (and therefore your problem). But, you need a local network with DHCP that gives access to the Internet. If you are directly connected to the device and need manual configuration, you can still do it via ssh.

**Comment by BenoitAnastay** [comment]
```
If you are directly connected to the device and need manual configuration, you can still do it via ssh.
```

It's what I did

**Comment by angt** [comment]
Good :)
