### ISSUE TITLE
iPhone tethering not working on General public stable

### ISSUE THREAD

**Issue by sirdharma** [ovh/overthebox#201]
Hi,

First of all, I am sorry to be asking in GitHub what should be a support request but I have had a ticket opened with OVH since November 19 and no answer since.

I am running overthebox General public stable on OVH-provided hardware (OverTheBox Plus) and am running into the following issue when trying to tether from my iPhone: `usbnet: ipheth: prevent TX queue timeouts when device not ready`. This issue is documented in the LKML: https://lkml.org/lkml/2019/5/2/563 and was apparently patched in kernel `4.9.173`.

As far as I can tell, the General public stable branch runs kernel `4.9.58`. From my OVH dashboard I can apparently change version but nowhere in the documentation does it explain which branch each version targets and if it's safe to run on my hardware.

![Screenshot 2020-12-04 at 11 07 42](https://user-images.githubusercontent.com/260721/101150730-f0b24380-3620-11eb-9c80-611b6b4d273f.png)

Could you please let me know what the "Beta", "Alpha" and "Development" versions are?

Thanks!
François

**Comment by AxelDum** [comment]
This issue has been fixed with release v0.8
