### ISSUE TITLE
QOS not working

### ISSUE THREAD

**Issue by MetallianFR68** [ovh/overthebox#34]
I just installed my OVERTHEBOX with an OVH ADSL connection and a second 4G connection.
I connected my server behind the OVERTHEBOX (mail server, webdav server)

My server starts an external backup every night at 11:00PM through SSH and RSYNC.
When it starts, it consumes all the bandwidth and all other services (webdav and mail) are very very slow.
So I created a rule to make the backup traffic low priority.
My idea was to assign every traffic at destination port 22 to the traffic class SC1 - SCAVENGER.
But it doesn't work, even after a clean reboot.
I can clearly see in the QOS graph that it is always routed as SC2 - NORMAL

I also tried to do it differently by assigning SC1 to every traffic sent to my backup server's IP address.
It doesn't work either.

What am I doing wrong ?

Subsidiary question : in the QOS GRAPHS, where is SC5 - BROADCAST VIDEO ? I can't see it anywhere.

Thanks for yo answers

**Comment by sduponch** [comment]
Hi, for now CS4 and CS5 share exactly the same OoS queue but later the difference will be on multipath scheduler choice. One will be for lowest ping (packet duplicated on all path) and the other for aggregated bandwith (defaullt scheduler).

To get QoS active you need to manually set connection speed under Network -> Interfaces -> Traffic control.

**Comment by MetallianFR68** [comment]
My backup just started on port 22 on my external computer.
Here's what appears in the REALTIME CONNECTIONS page :

Network	Protocol	Source	Destination	Transfer
IPV4	TCP	adaris.org:48399	10.166.178.2:22	203.14 MB (266039 Pkts.)

What is that destination address 10.166.178.2 ?
This doesn't make sense.
It's a private IP address.
It's not the Public IP address of my backup server
And I don't have any computer with 10.x.x.x addresses. Everything is setup with 192.x
What are those 10.x addresses ?

**Comment by sduponch** [comment]
This is the overthebox tunnel address, this address act like a router : 
- local network -> (lan) OTB (tun0) -> ISP Modems -> (tun0) OTB Service (public ip) -> Internet

**Comment by sduponch** [comment]
There was a bug in the configure processor that does not create the xtun0 interface
https://github.com/ovh/overthebox-feeds/pull/227
