### ISSUE TITLE
UDP TIMEOUT Value

### ISSUE THREAD

**Issue by MetallianFR68** [ovh/overthebox#36]
Hi,

In order for the OVH VOIP service to work, udp timeout must be set to 180 seconds or higher

There's no way to modify this setting in the OTB LUCI interface

I checked in /etc/sysctl.conf and i found:
net.netfilter.nf_conntrack_udp_timeout=60

Does that mean that UDP TIMEOUT is set at 60 by default (which is not compatible with OVH VOIP) ?

How do I change this value ?

**Comment by sduponch** [comment]
Hi, there is two value for udp timeout :

net.netfilter.nf_conntrack_udp_timeout = 60
net.netfilter.nf_conntrack_udp_timeout_stream = 180
