### ISSUE TITLE
Traffic Rule - VOIP

### ISSUE THREAD

**Issue by MetallianFR68** [ovh/overthebox#38]
IN my OTB Load Balancing settings I can see a rule named voip

voip
91.121.128.0/23
udp
failover

First question: why 91.121.128.0/23 ?
Isn't it supposed to be 91.121.12**9**.0/23 ?
I connect to sip3.ovh.fr which IP address is 91.121.129.159

Second question: what exactly is the failover policy.
I see that it is by default configured as : tun0_m1_w1, if1_m2_w1, if2_m3_w1
Does it mean that it doesn't aggregate the connections ?
Does it only use one if1 ?
What is the tun0 interface ?

**Comment by sduponch** [comment]
Hi,
- Isn't it supposed to be 91.121.129.0/23 ?
```
sduponch@desk539609:~$ whois 91.121.129.159 | grep inet
inetnum:        91.121.128.0 - 91.121.129.255

Network:   91.121.128.0/23       01011011.01111001.1000000 0.00000000 (Class A)
Broadcast: 91.121.129.255        01011011.01111001.1000000 1.11111111
HostMin:   91.121.128.1          01011011.01111001.1000000 0.00000001
HostMax:   91.121.129.254        01011011.01111001.1000000 1.11111110
```
-  Does it mean that it doesn't aggregate the connections ?
Aggregation is done through tun0 by glorytun, mwan is only used for failover.
-  Does it only use one if1 ?
Mwan policies are used only for "failover", that mean that if tun0 is down, then OTB will use only if1 and if if1 goes down then OTB use only if2.
-  What is the tun0 interface ?
(x)tun0 interfaces are tunnel interfaces that will do aggregation using glorytun and mptcp (in tcp version you should have tun0 and xtun0, where xtun0 is used for VoIP). We have in beta test an udp version of glorytun optimized for VoIP with better QoS management.

**Comment by MetallianFR68** [comment]
Thanks for these very useful answers !
